/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alternative Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.videoGen.AlternativeImage#getImageid <em>Imageid</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.videoGen.AlternativeImage#getImages <em>Images</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativeImage()
 * @model
 * @generated
 */
public interface AlternativeImage extends Image
{
  /**
   * Returns the value of the '<em><b>Imageid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imageid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imageid</em>' attribute.
   * @see #setImageid(String)
   * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativeImage_Imageid()
   * @model
   * @generated
   */
  String getImageid();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.videoGen.AlternativeImage#getImageid <em>Imageid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imageid</em>' attribute.
   * @see #getImageid()
   * @generated
   */
  void setImageid(String value);

  /**
   * Returns the value of the '<em><b>Images</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.videoGen.ImageDescription}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Images</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Images</em>' containment reference list.
   * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativeImage_Images()
   * @model containment="true"
   * @generated
   */
  EList<ImageDescription> getImages();

} // AlternativeImage
