/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.videoGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getImage()
 * @model
 * @generated
 */
public interface Image extends Media
{
} // Image
