/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.videoGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Media</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getMedia()
 * @model
 * @generated
 */
public interface Media extends EObject
{
} // Media
